### ISSUE TITLE
icd-git: not authorized

### ISSUE THREAD

**Issue by lianqiw** [tmtsoftware/icd#39]
When I push using icd-git, it says not authorized. However, I can manually clone the  repository and push new files https://github.com/tmt-icd/AOESW-Model-Files

OK. I realized that this this command is only intended for SE to publish finalized ICDs. I will close the issue.

Here is the message:

```icd-git --subsystems AOESW --publish --user lianqiw --password ******** --comment "Initial draft"

org.eclipse.jgit.api.errors.TransportException: https://github.com/tmt-icd/ICD-Model-Files: not authorized
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:169)
	at csw.services.icd.github.IcdGitManager$.publish(IcdGitManager.scala:355)
	at csw.services.icd.github.IcdGit$.publish(IcdGit.scala:290)
	at csw.services.icd.github.IcdGit$.run(IcdGit.scala:125)
	at csw.services.icd.github.IcdGit$.delayedEndpoint$csw$services$icd$github$IcdGit$1(IcdGit.scala:107)
	at csw.services.icd.github.IcdGit$delayedInit$body.apply(IcdGit.scala:10)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at csw.services.icd.github.IcdGit$.main(IcdGit.scala:10)
	at csw.services.icd.github.IcdGit.main(IcdGit.scala)
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/tmt-icd/ICD-Model-Files: not authorized
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:491)
	at org.eclipse.jgit.transport.TransportHttp.openPush(TransportHttp.java:379)
	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:155)
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1250)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:158)

```

**Comment by abrighton** [comment]
Note also that there is an interactive option that will let you type in the password in a way that is not visible.
