### ISSUE TITLE
No file or line information when ingesting invalid command with no type specified

### ISSUE THREAD

**Issue by edwardchapin** [tmtsoftware/icd#55]
This is another validation issue. We had a case where someone forgot to specify the type of an attribute in a command, e.g.,
```
subsystem = NFIRAOS
component = at

description = Alignment Telescope (AT) Assembly commands.

receive = [
  
  {
    name            = init
    description     = """Prepares the assembly for operation and reads configuration files."""
    args = [
       {
        name        = configName 
        description = Name of the configuration file to get from the TMT Configuration Service
      }
    ]
  }
]
```

It is missing `type = string` in the argument definition. When I ingest the component directory I get the following exception:
```
$ icd-db -i .
java.lang.NullPointerException
	at csw.services.icd.IcdValidator$.$anonfun$formatMsg$1(IcdValidator.scala:219)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:448)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.TraversableOnce.addString(TraversableOnce.scala:357)
	at scala.collection.TraversableOnce.addString$(TraversableOnce.scala:353)
	at scala.collection.AbstractIterator.addString(Iterator.scala:1417)
	at scala.collection.TraversableOnce.mkString(TraversableOnce.scala:323)
	at scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:322)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1417)
	at scala.collection.TraversableOnce.mkString(TraversableOnce.scala:325)
	at scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:325)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1417)
	at csw.services.icd.IcdValidator$.formatMsg(IcdValidator.scala:220)
	at csw.services.icd.IcdValidator$.$anonfun$validateResult$1(IcdValidator.scala:195)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at csw.services.icd.IcdValidator$.validateResult(IcdValidator.scala:194)
	at csw.services.icd.IcdValidator$.validate(IcdValidator.scala:182)
	at csw.services.icd.IcdValidator$.validate(IcdValidator.scala:175)
	at csw.services.icd.IcdValidator$.$anonfun$validate$1(IcdValidator.scala:98)
	at scala.collection.immutable.List.map(List.scala:287)
	at csw.services.icd.IcdValidator$.validate(IcdValidator.scala:86)
	at csw.services.icd.IcdValidator$.$anonfun$validateRecursive$1(IcdValidator.scala:73)
	at scala.collection.immutable.List.flatMap(List.scala:335)
	at csw.services.icd.IcdValidator$.validateRecursive(IcdValidator.scala:73)
	at csw.services.icd.db.IcdDb.ingest(IcdDb.scala:251)
	at csw.services.icd.db.IcdDb$.$anonfun$run$1(IcdDb.scala:111)
	at scala.Option.map(Option.scala:146)
	at csw.services.icd.db.IcdDb$.run(IcdDb.scala:111)
	at csw.services.icd.db.IcdDb$.delayedEndpoint$csw$services$icd$db$IcdDb$1(IcdDb.scala:98)
	at csw.services.icd.db.IcdDb$delayedInit$body.apply(IcdDb.scala:20)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at csw.services.icd.db.IcdDb$.main(IcdDb.scala:20)
	at csw.services.icd.db.IcdDb.main(IcdDb.scala)
fatal: java.lang.NullPointerException
```

I'm guessing this is similar to #45 and #51. Even if it isn't possible for it to give a more detailed error message (like `Attribute missing type field required by schema at line ...`), it should at least tell us the **file name** (it can be quite hard to find when you are ingesting an entire subsystem, and you have no idea which component the error is in).

**Comment by abrighton** [comment]
Fixed in IcdValidator.scala and checked in to master branch.

**Comment by edwardchapin** [comment]
Thanks, I confirm that this patch works on our end.
